# Generated by Django 6.0.6 on 2026-06-20 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tombe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tombe', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('Disponible', 'Disponible'), ('Réservée', 'Réservée'), ('Occupée', 'Occupée'), ('NonExploitable', 'Zone non exploitable')], default='Disponible', max_length=20)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('coordonnee_x', models.FloatField()),
                ('coordonnee_y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_zone', models.CharField(max_length=100)),
                ('code_zone', models.CharField(max_length=10, unique=True)),
                ('superficie', models.FloatField(help_text='Superficie totale en m²')),
                ('longueur', models.FloatField()),
                ('largeur', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_client', models.EmailField(max_length=254)),
                ('nom_defunt_prevu', models.CharField(max_length=100)),
                ('prenom_defunt_prevu', models.CharField(max_length=100)),
                ('date_enterrement', models.DateField(blank=True, null=True)),
                ('montant_devis', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut_demande', models.CharField(default='En attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('devis_pdf', models.FileField(blank=True, null=True, upload_to='documents/devis/')),
                ('recu_pdf', models.FileField(blank=True, null=True, upload_to='documents/recus/')),
                ('tombe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.tombe')),
            ],
        ),
        migrations.CreateModel(
            name='Defunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_enterrement', models.DateField()),
                ('tombe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defunt', to='gestion.tombe')),
            ],
        ),
        migrations.AddField(
            model_name='tombe',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tombes', to='gestion.zone'),
        ),
    ]
