# Generated by Django 6.0.6 on 2026-06-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_clientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
