"""Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/"""

from pathlib import Path
import os
#import sys
from dotenv import load_dotenv
import dj_database_url

# Charger les variables du fichier .env
load_dotenv()

# Configuration forcée pour GDAL et GEOS
#if os.name == 'nt':
#    os.environ['GDAL_LIBRARY_PATH'] = r'C:\OSGeo4W\bin\gdal313.dll'
#    os.environ['GEOS_LIBRARY_PATH'] = r'C:\OSGeo4W\bin\geos_c.dll'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Configuration des variables d'environnement ---
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False') == 'True'      
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp-relay.brevo.com')
#EMAIL_PORT = int(os.getenv('EMAIL_PORT', 465)) # Il prendra la valeur 465 de Render
#EMAIL_USE_TLS = False  # DOIT ÊTRE FALSE pour le port 465
#EMAIL_USE_SSL = True   # DOIT ÊTRE TRUE pour le port 465
EMAIL_TIMEOUT = 30
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Configuration Windows (pour ton PC uniquement)
if os.name == 'nt' and DEBUG:
    os.environ['GDAL_LIBRARY_PATH'] = r'C:\OSGeo4W\bin\gdal313.dll'
    os.environ['GEOS_LIBRARY_PATH'] = r'C:\OSGeo4W\bin\geos_c.dll'
    if r'C:\OSGeo4W\bin' not in os.environ['PATH']:
        os.environ['PATH'] = r'C:\OSGeo4W\bin;' + os.environ['PATH']

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

LOGIN_URL = 'gestion:login'
LOGIN_REDIRECT_URL = 'gestion:dashboard'
LOGOUT_REDIRECT_URL = 'gestion:login'

# --- Media files (PDF, images, etc.) ---
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'gestion-clients-cimeti-re.onrender.com']

STATIC_URL = '/static/'

# Chemin absolu vers ton dossier static global à la racine du projet
# Dans settings.py
STATICFILES_DIRS = [BASE_DIR / 'static',]

# Dossier où les fichiers seront collectés pour la production
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ninja',
    'core',
    'gestion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Garde uniquement le dossier global
        'APP_DIRS': True, # Cela suffit pour trouver core/templates/core/home.html
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


if not DEBUG:
    CSRF_TRUSTED_ORIGINS = ['https://gestion-clients-cimeti-re.onrender.com']
    SECURE_SSL_REDIRECT = True # Force le HTTPS

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_HTTPONLY = True

# 1. Force le HTTPS pour les cookies
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# 2. Permet au cookie d'être lu malgré les redirections (Crucial !)
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# 3. Assure-toi que ton domaine est bien reconnu
# Si tu as une erreur 403 CSRF, ajoute ceci :
CSRF_TRUSTED_ORIGINS = ['https://gestion-clients-cimeti-re.onrender.com']